name: 'Build Linux .deb Package'
description: 'Build Lemonade .deb package for Linux (minimal or full with Electron)'
inputs:
  include-electron:
    description: 'Whether to include the Electron app (full build)'
    required: false
    default: 'false'
outputs:
  package-name:
    description: 'The name of the generated .deb package file'
    value: ${{ steps.build-deb.outputs.package_name }}
runs:
  using: "composite"
  steps:
    - name: Run setup.sh to configure environment
      shell: bash
      run: |
        set -e

        echo "Running setup.sh to configure build environment..."
        bash setup.sh

        echo "Build environment configured successfully!"

    - name: Setup Node.js
      if: inputs.include-electron == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build C++ Server with CMake
      shell: bash
      run: |
        set -e

        echo "Building lemonade-router and lemonade-server for Linux..."

        # Reconfigure if Electron app is included (setup.sh already did basic config)
        if [ "${{ inputs.include-electron }}" == "true" ]; then
            echo "Reconfiguring CMake with Electron app enabled..."
            cmake --preset default -DBUILD_ELECTRON_APP=ON
        fi

        # Build (BUILD_ELECTRON_APP will trigger electron build automatically)
        echo "Building binaries..."
        cmake --build --preset default

        # Verify binaries exist
        if [ ! -f "build/lemonade-router" ]; then
            echo "ERROR: lemonade-router not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        if [ ! -f "build/lemonade-server" ]; then
            echo "ERROR: lemonade-server not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        echo "✓ Binaries found successfully"

        echo "Verifying binary executability..."
        ./build/lemonade-router --version
        ./build/lemonade-server --version

        echo "C++ build successful!"

    - name: Build .deb package
      id: build-deb
      shell: bash
      run: |
        set -e

        cd build

        echo "Creating .deb package with CPack..."
        cpack -G DEB -V

        # List generated files
        echo "Files in build directory:"
        ls -lh *.deb 2>/dev/null || echo "No .deb files found in current directory"

        # Determine expected package name based on build type
        if [ "${{ inputs.include-electron }}" == "true" ]; then
            DEB_FILE="lemonade_${LEMONADE_VERSION}_amd64.deb"
            PACKAGE_TYPE="full"
        else
            DEB_FILE="lemonade-server-minimal_${LEMONADE_VERSION}_amd64.deb"
            PACKAGE_TYPE="minimal"
        fi

        echo "Looking for: $DEB_FILE"

        if [ ! -f "$DEB_FILE" ]; then
            echo "ERROR: .deb package not created!"
            echo "Contents of build directory:"
            ls -lR .
            exit 1
        fi

        echo ".deb package ($PACKAGE_TYPE) created successfully!"
        ls -lh "$DEB_FILE"

        # Show package info
        echo "Package information:"
        dpkg-deb --info "$DEB_FILE"

        # Output the package name for subsequent steps
        echo "package_name=$DEB_FILE" >> $GITHUB_OUTPUT
