name: 'Build Linux .deb Package'
description: 'Build Lemonade .deb package for Linux'
outputs:
  package-name:
    description: 'The name of the generated .deb package file'
    value: ${{ steps.build-deb.outputs.package_name }}
runs:
  using: "composite"
  steps:
    - name: Run setup.sh to configure environment
      shell: bash
      run: |
        set -e

        echo "Running setup.sh to configure build environment..."
        bash setup.sh

        echo "Build environment configured successfully!"

    - name: Build C++ Server with CMake
      shell: bash
      run: |
        set -e

        echo "Building lemonade-router and lemonade-server for Linux..."

        # Build (BUILD_ELECTRON_APP will trigger electron build automatically)
        echo "Building binaries..."
        cmake --build --preset default

        # Verify binaries exist
        if [ ! -f "build/lemonade-router" ]; then
            echo "ERROR: lemonade-router not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        if [ ! -f "build/lemonade-server" ]; then
            echo "ERROR: lemonade-server not found!"
            echo "Build directory contents:"
            ls -lh build/
            exit 1
        fi

        echo "✓ Binaries found successfully"

        echo "Verifying binary executability..."
        ./build/lemonade-router --version
        ./build/lemonade-server --version

        echo "C++ build successful!"

    - name: Build .deb package
      id: build-deb
      shell: bash
      run: |
        set -e

        DEB_FILE="lemonade-server_${LEMONADE_VERSION}_amd64.deb"

        cd build

        echo "Creating .deb package with CPack..."
        cpack -G DEB -V

        echo "Looking for: $DEB_FILE"

        if [ ! -f "$DEB_FILE" ]; then
            echo "ERROR: .deb package not created!"
            echo "Contents of build directory:"
            ls -lR .
            exit 1
        fi

        # Show package info
        echo "Package information:"
        dpkg-deb --info "$DEB_FILE"

        # Output the package name for subsequent steps
        echo "package_name=$DEB_FILE" >> $GITHUB_OUTPUT
