name: Setup RyzenAI Server
description: Setup RyzenAI Server from already-downloaded artifact files for testing

inputs:
  install-path:
    description: 'The LEMONADE_INSTALL_PATH where RyzenAI Server should be installed'
    required: true
  artifact-path:
    description: 'Path where the ryzenai-server artifact files have been downloaded'
    required: false
    default: 'ryzenai-server-files'

runs:
  using: composite
  steps:
    - name: Setup RyzenAI Server for testing
      shell: PowerShell
      run: |
        Write-Host "Setting up ryzenai-server from artifact..." -ForegroundColor Cyan
        
        $artifactPath = "${{ inputs.artifact-path }}"
        
        # First, check what we have
        Write-Host "`nContents of artifact directory:" -ForegroundColor Yellow
        Get-ChildItem "$artifactPath" -File | ForEach-Object {
            $sizeMB = [math]::Round($_.Length / 1MB, 2)
            Write-Host "  - $($_.Name) ($sizeMB MB)" -ForegroundColor Gray
        }
        
        $ryzenaiDir = Join-Path "${{ inputs.install-path }}" "bin\ryzenai-server"
        
        # Create ryzenai-server directory
        New-Item -ItemType Directory -Path $ryzenaiDir -Force | Out-Null
        
        # Copy all files from artifact to ryzenai-server directory
        Write-Host "`nCopying ryzenai-server files to: $ryzenaiDir" -ForegroundColor Gray
        Copy-Item -Path "$artifactPath\*" -Destination $ryzenaiDir -Recurse -Force
        
        # Force filesystem sync and wait
        Start-Sleep -Seconds 2
        
        # Retry logic for verification
        $ryzenaiExe = Join-Path $ryzenaiDir "ryzenai-server.exe"
        $maxRetries = 5
        $retryCount = 0
        $found = $false
        
        while (-not $found -and $retryCount -lt $maxRetries) {
            if (Test-Path $ryzenaiExe) {
                $found = $true
                Write-Host "[OK] ryzenai-server.exe found at: $ryzenaiExe" -ForegroundColor Green
                
                # List a few files to confirm
                $fileCount = (Get-ChildItem $ryzenaiDir -File | Measure-Object).Count
                Write-Host "[OK] Total files in ryzenai-server directory: $fileCount" -ForegroundColor Green
            } else {
                $retryCount++
                Write-Host "Attempt ${retryCount}/${maxRetries}: ryzenai-server.exe not found yet, waiting..." -ForegroundColor Yellow
                Start-Sleep -Seconds 1
            }
        }
        
        if (-not $found) {
            Write-Host "ERROR: ryzenai-server.exe not found after ${maxRetries} attempts!" -ForegroundColor Red
            Write-Host "Contents of ryzenai-server directory:" -ForegroundColor Yellow
            Get-ChildItem $ryzenaiDir | Format-Table Name, Length
            Write-Host "`nContents of source directory:" -ForegroundColor Yellow
            Get-ChildItem "$artifactPath" | Format-Table Name, Length
            exit 1
        }

