name: 'Install Lemonade Server (MSI)'
description: 'Downloads and installs Lemonade Server MSI, then verifies installation'
inputs:
  install-path:
    description: 'Path where Lemonade Server should be installed'
    required: true
  artifact-name:
    description: 'Name of the artifact to download'
    required: false
    default: 'Lemonade_Server_MSI'

runs:
  using: "composite"
  steps:
    - name: Download Lemonade Server Installer
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: .

    - name: Install Lemonade Server
      shell: PowerShell
      run: |
        $installPath = "${{ inputs.install-path }}"
        $logPath = "$((Get-Location).Path)\lemonade-msi-install.log"
        Write-Host "Installing Lemonade Server to: $installPath" -ForegroundColor Cyan
        Write-Host "Log file will be at: $logPath" -ForegroundColor Gray

        if (-not (Test-Path "lemonade-server-minimal.msi")) {
            Write-Host "ERROR: lemonade-server-minimal.msi not found in current directory!" -ForegroundColor Red
            Get-ChildItem
            exit 1
        }

        # Run installer silently with verbose logging
        $args = "/i lemonade-server-minimal.msi /qn INSTALLDIR=`"$installPath`" /L*V `"$logPath`""
        $p = Start-Process -FilePath "msiexec.exe" -ArgumentList $args -Wait -PassThru

        if ($p.ExitCode -ne 0) {
             Write-Host "ERROR: Installation failed with exit code $($p.ExitCode)" -ForegroundColor Red

             if (Test-Path $logPath) {
                 Write-Host "=== MSI Install Log ($logPath) ===" -ForegroundColor Yellow
                 Get-Content $logPath
                 Write-Host "=== End MSI Install Log ===" -ForegroundColor Yellow
             } else {
                 Write-Host "ERROR: Log file not found at $logPath" -ForegroundColor Red
             }

             exit $p.ExitCode
        }

        Write-Host "Installation complete." -ForegroundColor Green

    - name: Verify Installation
      shell: PowerShell
      run: |
        $ErrorActionPreference = "Stop"
        $installPath = "${{ inputs.install-path }}"
        $logPath = "$((Get-Location).Path)\lemonade-msi-install.log"

        Write-Host "Verifying installation at: $installPath" -ForegroundColor Cyan

        # Function to print log on failure
        function Print-InstallLog {
            if (Test-Path $logPath) {
                Write-Host "=== MSI Install Log ($logPath) ===" -ForegroundColor Yellow
                Get-Content $logPath
                Write-Host "=== End MSI Install Log ===" -ForegroundColor Yellow
            } else {
                Write-Host "Log file not found at: $logPath" -ForegroundColor Red
            }
        }

        # Check if installation directory exists
        if (-not (Test-Path $installPath)) {
            Write-Host "ERROR: Installation directory not found at $installPath" -ForegroundColor Red
            Print-InstallLog
            exit 1
        }

        # Check for key binaries
        $expectedBinaries = @(
            "bin\lemonade-router.exe",
            "bin\lemonade-server.exe",
            "bin\lemonade-tray.exe"
        )

        $missingItems = @()
        foreach ($item in $expectedBinaries) {
            $fullPath = Join-Path $installPath $item
            if (-not (Test-Path $fullPath)) {
                $missingItems += $item
            } else {
                Write-Host "Found: $item" -ForegroundColor Green
            }
        }

        if ($missingItems.Count -gt 0) {
            Write-Host "ERROR: Missing expected files after installation:" -ForegroundColor Red
            foreach ($missing in $missingItems) {
                Write-Host "  Missing: $missing" -ForegroundColor Red
            }
            Print-InstallLog
            exit 1
        }

        Write-Host "Installation directory verification successful!" -ForegroundColor Green

    - name: Verify Server Version
      shell: PowerShell
      run: |
        $ErrorActionPreference = "Stop"
        $installPath = "${{ inputs.install-path }}"
        $serverExe = Join-Path $installPath "bin\lemonade-server.exe"

        Write-Host "Checking lemonade-server version..." -ForegroundColor Cyan

        try {
            # Capture output and exit code
            $process = Start-Process -FilePath $serverExe -ArgumentList "--version" -NoNewWindow -Wait -PassThru

            if ($process.ExitCode -ne 0) {
                Write-Host "ERROR: lemonade-server --version exited with code $($process.ExitCode)" -ForegroundColor Red
                exit 1
            }

            # Run again to capture output for display (Start-Process -PassThru doesn't easily capture stdout to variable without redirect)
            # Simpler approach for display:
            & $serverExe --version

            Write-Host "Version check passed (Exit Code 0)" -ForegroundColor Green

        } catch {
            Write-Host "ERROR: Failed to run version check: $_" -ForegroundColor Red
            exit 1
        }
